CREATE TABLE report_data (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    date DATE NOT NULL,
    day_week INTEGER,
    link_jadson_consumo FLOAT NOT NULL,
    link_df_consumo FLOAT NOT NULL,
    link_formosa_consumo FLOAT NOT NULL,
    clients_online INTEGER NOT NULL,
    clients_offline INTEGER NOT NULL,
    clients_blocked INTEGER NOT NULL,
    status_ar_is_ok BOOLEAN NOT NULL,
    switch_huawei_core_is_ok BOOLEAN NOT NULL,
    switch_datacom_link_is_ok BOOLEAN NOT NULL,
    bgp_is_ok BOOLEAN NOT NULL,
    concentrador_is_ok BOOLEAN NOT NULL,
    backup_server_is_ok BOOLEAN NOT NULL,
    a10_is_ok BOOLEAN NOT NULL,
    fonte1_is_ok BOOLEAN NOT NULL,
    fonte2_is_ok BOOLEAN NOT NULL,
    fonte3_is_ok BOOLEAN NOT NULL,
    quadro1_is_ok BOOLEAN NOT NULL,
    quadro2_is_ok BOOLEAN NOT NULL,
    quadro3_is_ok BOOLEAN NOT NULL,
    inversora_is_ok BOOLEAN NOT NULL,
    oltC300_is_ok BOOLEAN NOT NULL,
    oltC650_is_ok BOOLEAN NOT NULL,
    whatsapp_status VARCHAR(255) NOT NULL,
    system_manager_is_ok BOOLEAN NOT NULL,
    site_is_ok BOOLEAN NOT NULL,
    voip_is_ok BOOLEAN NOT NULL,
    devices_ont INTEGER NOT NULL,
    devices_local INTEGER NOT NULL
);